Reorg medusaget install script

diff --git a/medusaget/install b/medusaget/install
--- a/medusaget/install
+++ b/medusaget/install
@@ -1,48 +1,61 @@
 #!/usr/bin/env bash
 set -e
 
-echo Installing medusaget...
+function install_medusaget {
+  echo "Downloading medusaget..."
+  curl -# -k -L "$1" -o "$2"
+  chmod +x "$2"
+}
 
-# Base directories
-BASE_DIR=${XDG_CONFIG_HOME:-$HOME}
-MEDUSA_DIR=${MEDUSA_DIR-"$BASE_DIR/.medusa"}
-MEDUSA_BIN_DIR="$MEDUSA_DIR/bin"
+function configure_shell {
+  local shell_type="$1"
+  local bin_path="$2"
 
-# URL for medusaget script
-BIN_URL="https://raw.githubusercontent.com/crytic/medusa/master/medusaget/medusaget"
-BIN_PATH="$MEDUSA_BIN_DIR/medusaget"
+  case "$shell_type" in
+    zsh)
+      echo "export PATH=\$PATH:$bin_path" >> ~/.zshrc
+      ;;
+    bash)
+      echo "export PATH=\$PATH:$bin_path" >> ~/.bashrc
+      ;;
+    *)
+      echo "Unknown shell. Manually add to PATH."
+      exit 1
+      ;;
+  esac
+}
 
-# Create directories if they don't exist
-mkdir -p $MEDUSA_BIN_DIR
+function check_libusb_macos {
+  if [[ ! -f /usr/local/opt/libusb/lib/libusb-1.0.0.dylib && ! -f /opt/homebrew/opt/libusb/lib/libusb-1.0.0.dylib ]]; then
+    echo "Warning: libusb not found. You may need to install it manually via Homebrew (brew install libusb)."
+  fi
+}
 
-# Download medusaget script
-curl -# -L $BIN_URL -o $BIN_PATH
-chmod +x $BIN_PATH
+function main {
+  # Configurations
+  base_dir=${XDG_CONFIG_HOME:-$HOME}
+  root_dir="$base_dir/.medusa"
+  bin_dir="$root_dir/bin"
+  fetch_url="https://raw.githubusercontent.com/zachmdsi/medusa/feat/one-line-install/medusaget/medusaget"
+  fetch_path="$bin_dir/medusaget"
 
-# Detect shell and update profile
-case $SHELL in
-  */zsh)
-    PROFILE=${ZDOTDIR-"$HOME"}/.zshenv
-    PREF_SHELL=zsh
-    ;;
-  */bash)
-    PROFILE=$HOME/.bashrc
-    PREF_SHELL=bash
-    ;;
-  */fish)
-    PROFILE=$HOME/.config/fish/config.fish
-    PREF_SHELL=fish
-    ;;
-  *)
-    echo "Medusaget: could not detect shell, manually add ${MEDUSA_BIN_DIR} to your PATH."
-    exit 1
-esac
+  # Create dir & Download medusaget
+  mkdir -p "$bin_dir"
+  install_medusaget "$fetch_url" "$fetch_path"
 
-# Add medusaget to PATH if not already present
-if [[ ":$PATH:" != *":${MEDUSA_BIN_DIR}:"* ]]; then
-    echo >> $PROFILE && echo "export PATH=\"\$PATH:$MEDUSA_BIN_DIR\"" >> $PROFILE
-fi
+  # Shell & PATH setup
+  case "$SHELL" in
+    *zsh)  sh_type="zsh"  ;;
+    *bash) sh_type="bash" ;;
+    *)     sh_type="unknown" ;;
+  esac
+  configure_shell "$sh_type" "$bin_dir"
 
-echo "Detected your preferred shell is ${PREF_SHELL} and added medusaget to PATH."
-echo "Run 'source ${PROFILE}' or start a new terminal session to use medusaget."
-echo "Then, simply run 'medusaget' to start using it."
+  # MacOS libusb check
+  [[ "$OSTYPE" =~ ^darwin ]] && check_libusb_macos
+
+  echo "medusaget is ready. Simply run 'medusaget' to get started."
+}
+
+main "$@"
+
